#!/usr/bin/env bash
# Populate .env from Terraform outputs + Azure CLI.
# Run once after `terraform apply` to get the control plane ready.
#
# Usage: ./scripts/setup-env.sh [--sp-name <name>]
#   --sp-name  Name for the Azure service principal (default: az-spot-orch)
set -euo pipefail

SP_NAME="az-spot-orch"
while [[ $# -gt 0 ]]; do
  case $1 in
    --sp-name) SP_NAME="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"
ENV_FILE="$REPO_ROOT/.env"

echo "==> Reading Terraform outputs..."
cd "$TF_DIR"
COSMOS_ENDPOINT=$(terraform output -raw cosmos_endpoint)
COSMOS_KEY=$(terraform output -raw cosmos_primary_key)
CONTROL_PLANE_IP=$(terraform output -raw control_plane_public_ip)
RESOURCE_GROUP=$(terraform output -raw resource_group_name)

echo "==> Reading Azure account info..."
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)

echo "==> Creating service principal '$SP_NAME'..."
SP_JSON=$(az ad sp create-for-rbac \
  --name "$SP_NAME" \
  --role Contributor \
  --scopes "/subscriptions/$SUBSCRIPTION_ID" \
  --output json 2>/dev/null || true)

if [[ -z "$SP_JSON" ]]; then
  echo "    SP already exists — fetching existing credentials..."
  CLIENT_ID=$(az ad sp list --display-name "$SP_NAME" --query '[0].appId' -o tsv)
  echo "    WARNING: Cannot retrieve existing client secret. Set AZURE_CLIENT_SECRET manually."
  CLIENT_SECRET="REPLACE_ME"
else
  CLIENT_ID=$(echo "$SP_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['appId'])")
  CLIENT_SECRET=$(echo "$SP_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")
fi

SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub 2>/dev/null || cat ~/.ssh/id_ed25519.pub 2>/dev/null || echo "REPLACE_ME")

echo "==> Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-env.sh — do not commit this file.

# Azure Cosmos DB
COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
COSMOS_KEY=${COSMOS_KEY}

# Azure service principal
AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
AZURE_TENANT_ID=${TENANT_ID}
AZURE_CLIENT_ID=${CLIENT_ID}
AZURE_CLIENT_SECRET=${CLIENT_SECRET}

# Azure resource defaults
AZURE_RESOURCE_GROUP=${RESOURCE_GROUP}
AZURE_SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}

# Temporal (docker-compose overrides TEMPORAL_HOST for containers)
TEMPORAL_HOST=localhost:7233
TEMPORAL_NAMESPACE=default
TEMPORAL_TASK_QUEUE=vm-provisioning

# Control plane public URL (embedded into cloud-init for Spot VM callbacks)
CONTROL_PLANE_URL=http://${CONTROL_PLANE_IP}:8000

# Default VM size for Spot instances
DEFAULT_VM_SIZE=Standard_NC4as_T4_v3
EOF

echo ""
echo "Done. .env written."
[[ "$CLIENT_SECRET" == "REPLACE_ME" ]] && echo "ACTION NEEDED: set AZURE_CLIENT_SECRET in .env manually."
echo ""
echo "Next steps:"
echo "  1. Copy .env to the control-plane VM:"
echo "     scp .env azureuser@${CONTROL_PLANE_IP}:~/az-spot-orchestrator/"
echo "  2. SSH in and start the stack:"
echo "     ssh azureuser@${CONTROL_PLANE_IP}"
echo "     cd az-spot-orchestrator && docker compose up -d"
